Chore/format code
PolyglotDevsLondon/listings-app pull request #126
Opened 2021-02-12 14:36 UTC by louiechristie

- [x] This PR follows [contributing quidelines](CONTRIBUTING.md)
- [ ] This PR has tests (for backend in particular)

### What change does this PR introduce?

Autoformat code (HTML, SCSS, markdown, JavaScript.)

Old code formatted, and VSCode settings changed to autoformat new code on save 

### Notes

* Open some code in VSCode
* Install the recommended extensions (Prettier and Beautify)
* Edit some code, HTML, SCSS, markdown or JavaScript.
* Save it - the code should autoformat nicely.

### Ticket

- [Trello Ticket](https://trello.com/c/KuFBknWk/122-autoformat-code-html-scss-markdown-javascript)

### Screenshots

https://user-images.githubusercontent.com/6807448/107781154-78ae7b00-6d3f-11eb-8186-17913a275bc4.mp4

2021-02-12 18:11 UTC, tsvetelinak0 requested changes
left some notes to be clarified..in the meantime agree with the suggestions and approve the changes!

2021-02-12 18:11 UTC, tsvetelinak0 commented on CONTRIBUTING.md
>  - [Git offical documentation](https://git-scm.com/)
light old typo here..  should be official not offical :)

2021-02-12 18:11 UTC, tsvetelinak0 commented on src/components/index.js
> +  console.log("****** initComponents() ******");
js-files are indented with 2 spaces when the indent is set to 4 spaces?

2021-02-12 18:11 UTC, tsvetelinak0 commented on src/styles/base/_variables.scss
> +  base: 16,
I know this is old but would like to ask here when we specify the root variables I think we are missing the units, e.g. px, em, rem, %? otherwise we have only numbers which I guess the browser doesn't apply correctly?

2021-02-12 18:11 UTC, tsvetelinak0 commented on src/styles/components/_amenity_rating.scss
> +  &-icon {
...and the scss files are going from 4 to 2 indentation spaces? Lead dev have the final word, as far as I remember we agreed to 4 spaces at the beginning? need to check with @lili2311 ;)

2021-02-19 12:50 UTC, louiechristie commented on src/styles/components/_amenity_rating.scss
> +  &-icon {
Think we discussed this in the last meeting and Lilly said 2 spaces was fine.

2021-02-22 17:33 UTC, louiechristie commented on CONTRIBUTING.md
>  - [Git offical documentation](https://git-scm.com/)
I updated this in a separate hot-fix commit here: https://github.com/PolyglotDevsLondon/sharespots/commit/083f61b7a291fa483ddc99a5359d5da98463b19e

2021-02-22 17:34 UTC, louiechristie commented on src/components/index.js
> +  console.log("****** initComponents() ******");
See https://github.com/PolyglotDevsLondon/sharespots/pull/126#discussion_r579161539

2021-02-22 17:37 UTC, louiechristie commented on src/styles/base/_variables.scss
> +  base: 16,
@tsvetelinak0 I think you are right. I searched and looks like $base-font-size isn't actually being used. Can you create a new Trello ticket for updating this, and for also doing breakpoints as CSS variables and generally auditing that css variables are being used correctly?

2021-02-22 17:40 UTC, louiechristie commented
> left some notes to be clarified..

@tsvetelinak0 I've made some updates and left some replies to your comments. Please can you click on 'Resolve Conversation' if you are happy with my replies.

Please can you review again and approve?

2021-02-22 21:53 UTC, tsvetelinak0 approved these changes
looks great! neat and tidy! good to go! 💯

2021-02-22 21:56 UTC, tsvetelinak0 commented on src/styles/base/_variables.scss
> +  base: 16,
ace! sure will keep an eye!

2021-02-22 21:57 UTC, tsvetelinak0 commented on src/components/index.js
> +  console.log("****** initComponents() ******");
👌

2021-02-22 21:57 UTC, tsvetelinak0 commented on src/styles/components/_amenity_rating.scss
> +  &-icon {
💯

2021-02-23 09:02 UTC, merged